#Working on Real Project with Python - Data Analysis with Cars Dataset

**We are going to analyse data set pf cars using pandas dataframe**

In [36]:
import pandas as pd

In [74]:
df=pd.read_csv('/content/project-2 data analysis cars dataset.csv')
df.head(45)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170.0,22.0,31.0,3252.0,104.0,179.0
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170.0,23.0,30.0,3638.0,105.0,180.0
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220.0,20.0,28.0,3462.0,104.0,179.0
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220.0,17.0,26.0,3583.0,104.0,179.0
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220.0,18.0,25.0,3627.0,104.0,179.0
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220.0,20.0,27.0,3561.0,109.0,192.0
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220.0,18.0,25.0,3880.0,109.0,192.0
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220.0,20.0,27.0,3814.0,105.0,180.0
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220.0,18.0,25.0,4013.0,105.0,180.0
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250.0,18.0,25.0,3836.0,109.0,192.0
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300.0,17.0,24.0,4024.0,109.0,193.0
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330.0,17.0,24.0,4399.0,121.0,204.0
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340.0,14.0,20.0,3825.0,104.0,179.0
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450.0,15.0,22.0,4024.0,109.0,191.0
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180.0,20.0,28.0,3131.0,95.0,159.0
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225.0,20.0,28.0,2921.0,96.0,159.0
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250.0,21.0,29.0,3351.0,96.0,159.0
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220.0,18.0,25.0,4035.0,109.0,192.0
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340.0,15.0,21.0,3936.0,104.0,179.0
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225.0,16.0,23.0,4023.0,110.0,180.0
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325.0,16.0,22.0,4824.0,111.0,184.0
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184.0,20.0,29.0,3219.0,107.0,176.0
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184.0,20.0,29.0,3197.0,107.0,177.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184.0,19.0,27.0,3560.0,107.0,177.0
32,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184.0,19.0,27.0,3461.0,107.0,176.0
33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225.0,20.0,30.0,3285.0,107.0,176.0
34,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225.0,20.0,30.0,3285.0,107.0,176.0
35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225.0,20.0,29.0,3483.0,107.0,176.0
36,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.0,184.0,19.0,28.0,3428.0,114.0,191.0
37,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225.0,19.0,28.0,3616.0,107.0,177.0
38,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.0,225.0,20.0,30.0,3472.0,114.0,191.0
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.0,325.0,18.0,26.0,3814.0,114.0,191.0
41,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8.0,325.0,18.0,26.0,4376.0,118.0,198.0
42,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.0,325.0,18.0,26.0,4464.0,123.0,204.0
43,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6.0,333.0,16.0,24.0,3415.0,108.0,177.0
44,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.0,333.0,16.0,23.0,3781.0,108.0,177.0


**Data cleaning**
  
   
> Find the null values in the data set.If there is any null value in any column then, fill it with the mean of that column

In [76]:
df.shape

(432, 15)

In [77]:
df.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [78]:
df = df.dropna(axis=0)
df.head(35)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170.0,22.0,31.0,3252.0,104.0,179.0
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170.0,23.0,30.0,3638.0,105.0,180.0
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220.0,20.0,28.0,3462.0,104.0,179.0
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220.0,17.0,26.0,3583.0,104.0,179.0
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220.0,18.0,25.0,3627.0,104.0,179.0
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220.0,20.0,27.0,3561.0,109.0,192.0
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220.0,18.0,25.0,3880.0,109.0,192.0
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220.0,20.0,27.0,3814.0,105.0,180.0
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220.0,18.0,25.0,4013.0,105.0,180.0
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250.0,18.0,25.0,3836.0,109.0,192.0
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300.0,17.0,24.0,4024.0,109.0,193.0
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330.0,17.0,24.0,4399.0,121.0,204.0
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340.0,14.0,20.0,3825.0,104.0,179.0
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450.0,15.0,22.0,4024.0,109.0,191.0
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180.0,20.0,28.0,3131.0,95.0,159.0
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225.0,20.0,28.0,2921.0,96.0,159.0
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250.0,21.0,29.0,3351.0,96.0,159.0
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220.0,18.0,25.0,4035.0,109.0,192.0
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340.0,15.0,21.0,3936.0,104.0,179.0
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225.0,16.0,23.0,4023.0,110.0,180.0
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325.0,16.0,22.0,4824.0,111.0,184.0
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184.0,20.0,29.0,3219.0,107.0,176.0
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184.0,20.0,29.0,3197.0,107.0,177.0
31,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184.0,19.0,27.0,3560.0,107.0,177.0
32,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184.0,19.0,27.0,3461.0,107.0,176.0
33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225.0,20.0,30.0,3285.0,107.0,176.0
34,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225.0,20.0,30.0,3285.0,107.0,176.0
35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225.0,20.0,29.0,3483.0,107.0,176.0

In [79]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [80]:
df.shape

(426, 15)

**Check what are the differnt types of Make are there in our dataset and what is the count (occurance) of each Make in the data**

In [81]:
df.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0

In [82]:
df['Make'].value_counts()

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Hyundai          12
Jaguar           12
Volvo            12
Subaru           11
Pontiac          11
Lexus            11
Kia              11
Lincoln           9
Buick             9
Mazda             9
Mercury           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: Make, dtype: int64

**Filtering**


> **show all the record where origins are USA and Europe**

In [83]:
df[df['Origin'].isin(['USA','Europe'])].iloc[25:60:2]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225.0,20.0,30.0,3285.0,107.0,176.0
35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225.0,20.0,29.0,3483.0,107.0,176.0
37,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225.0,19.0,28.0,3616.0,107.0,177.0
40,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.0,325.0,18.0,26.0,3814.0,114.0,191.0
42,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.0,325.0,18.0,26.0,4464.0,123.0,204.0
44,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.0,333.0,16.0,23.0,3781.0,108.0,177.0
46,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.0,6.0,225.0,21.0,29.0,2998.0,98.0,161.0
48,Buick,Rainier,SUV,USA,All,"$37,895","$34,357",4.2,6.0,275.0,15.0,21.0,4600.0,113.0,193.0
50,Buick,Century Custom 4dr,Sedan,USA,Front,"$22,180","$20,351",3.1,6.0,175.0,20.0,30.0,3353.0,109.0,195.0
52,Buick,Regal LS 4dr,Sedan,USA,Front,"$24,895","$22,835",3.8,6.0,200.0,20.0,30.0,3461.0,109.0,196.0
54,Buick,LeSabre Limited 4dr,Sedan,USA,Front,"$32,245","$29,566",3.8,6.0,205.0,20.0,29.0,3591.0,112.0,200.0
56,Buick,Park Avenue Ultra 4dr,Sedan,USA,Front,"$40,720","$36,927",3.8,6.0,240.0,18.0,28.0,3909.0,114.0,207.0
58,Cadillac,SRX V8,SUV,USA,Front,"$46,995","$43,523",4.6,8.0,320.0,16.0,21.0,4302.0,116.0,195.0
60,Cadillac,Deville 4dr,Sedan,USA,Front,"$45,445","$41,650",4.6,8.0,275.0,18.0,26.0,3984.0,115.0,207.0
62,Cadillac,Seville SLS 4dr,Sedan,USA,Front,"$47,955","$43,841",4.6,8.0,275.0,18.0,26.0,3992.0,112.0,201.0
64,Cadillac,Escalade EXT,Truck,USA,All,"$52,975","$48,541",6.0,8.0,345.0,13.0,17.0,5879.0,130.0,221.0
66,Chevrolet,Tahoe LT,SUV,USA,All,"$41,465","$36,287",5.3,8.0,295.0,14.0,18.0,5050.0,116.0,197.0
68,Chevrolet,Tracker,SUV,USA,Front,"$20,255","$19,108",2.5,6.0,165.0,19.0,22.0,2866.0,98.0,163.0

**Removing unwanted records from the dataset**


> like Remove all the records(rows) where weight is more than 4000

In [89]:
df[df['Weight']<5000]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [88]:
df[~(df['Weight']<5000)]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
57,Cadillac,Escalade,SUV,USA,Front,"$52,795","$48,377",5.3,8.0,295.0,14.0,18.0,5367.0,116.0,199.0
64,Cadillac,Escalade EXT,Truck,USA,All,"$52,975","$48,541",6.0,8.0,345.0,13.0,17.0,5879.0,130.0,221.0
66,Chevrolet,Tahoe LT,SUV,USA,All,"$41,465","$36,287",5.3,8.0,295.0,14.0,18.0,5050.0,116.0,197.0
86,Chevrolet,Avalanche 1500,Truck,USA,All,"$36,100","$31,689",5.3,8.0,295.0,14.0,18.0,5678.0,130.0,222.0
120,Ford,Excursion 6.8 XLT,SUV,USA,All,"$41,475","$36,494",6.8,10.0,310.0,10.0,13.0,7190.0,137.0,227.0
121,Ford,Expedition 4.6 XLT,SUV,USA,Front,"$34,560","$30,468",4.6,8.0,232.0,15.0,19.0,5000.0,119.0,206.0
139,Ford,F-150 Supercab Lariat,Truck,USA,All,"$33,540","$29,405",5.4,8.0,300.0,14.0,18.0,5464.0,133.0,218.0
144,GMC,Yukon 1500 SLE,SUV,USA,Front,"$35,725","$31,361",4.8,8.0,285.0,16.0,19.0,5042.0,116.0,199.0
145,GMC,Yukon XL 2500 SLT,SUV,USA,All,"$46,265","$40,534",6.0,8.0,325.0,13.0,17.0,6133.0,130.0,219.0
149,GMC,Sierra HD 2500,Truck,USA,All,"$29,322","$25,759",6.0,8.0,300.0,13.0,18.0,5440.0,133.0,222.0
169,Hummer,H2,SUV,USA,All,"$49,995","$45,815",6.0,8.0,316.0,10.0,12.0,6400.0,123.0,190.0
219,Land Rover,Range Rover HSE,SUV,Europe,All,"$72,250","$65,807",4.4,8.0,282.0,12.0,16.0,5379.0,113.0,195.0
223,Lexus,LX 470,SUV,Asia,All,"$64,800","$56,455",4.7,8.0,235.0,13.0,17.0,5590.0,112.0,193.0
233,Lincoln,Navigator Luxury,SUV,USA,All,"$52,775","$46,360",5.4,8.0,300.0,13.0,18.0,5969.0,119.0,206.0
255,Mercedes-Benz,G500,SUV,Europe,All,"$76,870","$71,540",5.0,8.0,292.0,13.0,14.0,5423.0,112.0,186.0
303,Nissan,Pathfinder Armada SE,SUV,Asia,Front,"$33,840","$30,815",5.6,8.0,305.0,13.0,19.0,5013.0,123.0,207.0
318,Nissan,Titan King Cab XE,Truck,Asia,All,"$26,650","$24,926",5.6,8.0,305.0,14.0,18.0,5287.0,140.0,224.0
378,Toyota,Sequoia SR5,SUV,Asia,All,"$35,695","$31,827",4.7,8.0,240.0,14.0,17.0,5270.0,118.0,204.0
381,Toyota,Land Cruiser,SUV,Asia,All,"$54,765","$47,986",4.7,8.0,325.0,13.0,17.0,5390.0,112.0,193.0
405,Volkswagen,Touareg V6,SUV,Europe,All,"$35,515","$32,243",3.2,6.0,220.0,15.0,20.0,5086.0,112.0,187.0
415,Volkswagen,Phaeton 4dr,Sedan,Europe,Front,"$65,000","$59,912",4.2,8.0,335.0,16.0,22.0,5194.0,118.0,204.0
416,Volkswagen,Phaeton W12 4dr,Sedan,Europe,Front,"$75,000","$69,130",6.0,12.0,420.0,12.0,19.0,5399.0,118.0,204.0

In [90]:
df.shape

(426, 15)

In [92]:
426 - 404 #22 rows like it has given us above

22

**Applying function on a coloumn: In this if we want to make a change in any column value then we use apply function**


> **Increase all the values of MPG_Highway by 5 values**

In [95]:
df['MPG_Highway'] = df['MPG_Highway'].apply(lambda x:x+5)
df

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,33.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,41.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,39.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,38.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,34.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,38.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,36.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,36.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,39.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,37.0,3823.0,109.0,186.0